query GetOrders {
    orders {
        id
        orderDate
        description
        totalAmount
        depositAmount
        isDelivery
        status
        otherNotes
        customerId
        customer{
            firstName
            lastName
        }
    }
}